import type {
  CustomerDistributionSlice,
  CustomerInsight,
  CustomerKpi,
  CustomerRiskItem,
  CustomerRow,
} from '@/features/crm/types'

export const CUSTOMER_KPIS: CustomerKpi[] = [
  {
    id: 'total',
    labelKey: 'kpis.total',
    value: '12,450',
    trend: 'up',
    trendValue: '100%',
    chart: 'blue',
  },
  {
    id: 'active',
    labelKey: 'kpis.active',
    value: '10,890',
    subtextKey: 'kpis.ofTotal',
    subtextValue: '87%',
    chart: 'emerald',
  },
  {
    id: 'newMonth',
    labelKey: 'kpis.newMonth',
    value: '32',
    trend: 'up',
    trendValue: '23%',
    chart: 'indigo',
  },
  {
    id: 'installment',
    labelKey: 'kpis.installment',
    value: '5,630',
    subtextKey: 'kpis.ofTotal',
    subtextValue: '45%',
    chart: 'purple',
  },
  {
    id: 'late',
    labelKey: 'kpis.late',
    value: '124',
    trend: 'up',
    trendValue: '15%',
    chart: 'rose',
  },
  {
    id: 'inactive',
    labelKey: 'kpis.inactive',
    value: '87',
    trend: 'down',
    trendValue: '6%',
    chart: 'slate',
  },
]

export const CUSTOMER_RISKS: CustomerRiskItem[] = [
  {
    id: 'late',
    labelKey: 'risks.late',
    descriptionKey: 'risks.lateDesc',
    count: 124,
    variant: 'red',
  },
  {
    id: 'credit',
    labelKey: 'risks.credit',
    descriptionKey: 'risks.creditDesc',
    count: 38,
    variant: 'amber',
  },
  {
    id: 'noPurchase',
    labelKey: 'risks.noPurchase',
    descriptionKey: 'risks.noPurchaseDesc',
    count: 87,
    variant: 'orange',
  },
  {
    id: 'suspended',
    labelKey: 'risks.suspended',
    descriptionKey: 'risks.suspendedDesc',
    count: 56,
    variant: 'rose',
  },
  {
    id: 'review',
    labelKey: 'risks.review',
    descriptionKey: 'risks.reviewDesc',
    count: 23,
    variant: 'indigo',
  },
]

export const CUSTOMER_INSIGHTS: CustomerInsight[] = [
  {
    id: 'best',
    titleKey: 'insights.best',
    variant: 'emerald',
    name: 'شركة نور التجارية',
    amount: '125,000',
  },
  {
    id: 'trend',
    titleKey: 'insights.trend',
    variant: 'amber',
    messageKey: 'insights.trendMessage',
    messageValue: '15%',
  },
  {
    id: 'followUp',
    titleKey: 'insights.followUp',
    variant: 'blue',
    messageKey: 'insights.followUpMessage',
    messageValue: 87,
  },
]

export const CUSTOMER_DISTRIBUTION: CustomerDistributionSlice[] = [
  { id: 'individual', labelKey: 'distribution.individual', value: 42, color: '#0055ff' },
  { id: 'company', labelKey: 'distribution.company', value: 35, color: '#6366f1' },
  { id: 'government', labelKey: 'distribution.government', value: 15, color: '#10b981' },
  { id: 'other', labelKey: 'distribution.other', value: 8, color: '#f59e0b' },
]

export const DEMO_CUSTOMERS: CustomerRow[] = [
  {
    id: '1',
    customerId: 1,
    code: 'C0001',
    name: 'شركة الأمل للتجارة',
    phone: '0501234567',
    city: 'جدة',
    totalTransactions: 245,
    balanceDue: 12500,
    lastPurchaseDate: '2026-06-10',
    status: 'active',
    customerType: 'company',
    taxId: '300123456789003',
    branch: 'جدة الرئيسي',
    group: 'تجار الجملة',
    salesRep: 'محمد العتيبي',
  },
  {
    id: '2',
    customerId: 2,
    code: 'C0002',
    name: 'مؤسسة الخليج',
    phone: '0559876543',
    city: 'الرياض',
    totalTransactions: 89,
    balanceDue: 0,
    lastPurchaseDate: '2026-06-08',
    status: 'active',
    customerType: 'company',
    taxId: '300987654321003',
    branch: 'الرياض',
    group: 'تجزئة',
    salesRep: 'سارة الحربي',
  },
  {
    id: '3',
    customerId: 3,
    code: 'C0003',
    name: 'أحمد السعيد',
    phone: '0541112233',
    city: 'الدمام',
    totalTransactions: 34,
    balanceDue: 3200,
    lastPurchaseDate: '2026-05-15',
    status: 'suspended',
    customerType: 'individual',
    branch: 'الدمام',
    group: 'أفراد',
    salesRep: 'خالد الشمري',
  },
  {
    id: '4',
    customerId: 4,
    code: 'C0004',
    name: 'وزارة الصحة',
    phone: '0114567890',
    city: 'الرياض',
    totalTransactions: 12,
    balanceDue: 45000,
    lastPurchaseDate: '2026-04-20',
    status: 'under_review',
    customerType: 'government',
    taxId: '700123456789003',
    branch: 'الرياض',
    group: 'حكومي',
    salesRep: 'فهد القحطاني',
  },
  {
    id: '5',
    customerId: 5,
    code: 'C0005',
    name: 'شركة نور التجارية',
    phone: '0503334455',
    city: 'جدة',
    totalTransactions: 512,
    balanceDue: 0,
    lastPurchaseDate: '2026-06-12',
    status: 'active',
    customerType: 'company',
    taxId: '300555666777003',
    branch: 'جدة الرئيسي',
    group: 'تجار الجملة',
    salesRep: 'محمد العتيبي',
  },
  {
    id: '6',
    customerId: 6,
    code: 'C0006',
    name: 'مكتب الفجر',
    phone: '0532223344',
    city: 'مكة',
    totalTransactions: 67,
    balanceDue: 8900,
    lastPurchaseDate: '2026-03-01',
    status: 'blocked',
    customerType: 'other',
    branch: 'مكة',
    group: 'تجزئة',
    salesRep: 'نورة الزهراني',
  },
  {
    id: '7',
    customerId: 7,
    code: 'C0007',
    name: 'سعد الغامدي',
    phone: '0567778899',
    city: 'جدة',
    totalTransactions: 18,
    balanceDue: 1500,
    lastPurchaseDate: '2026-06-01',
    status: 'active',
    customerType: 'individual',
    branch: 'جدة الرئيسي',
    group: 'أفراد',
    salesRep: 'محمد العتيبي',
  },
  {
    id: '8',
    customerId: 8,
    code: 'C0008',
    name: 'شركة البحر الأحمر',
    phone: '0546667788',
    city: 'ينبع',
    totalTransactions: 156,
    balanceDue: 22000,
    lastPurchaseDate: '2026-05-28',
    status: 'suspended',
    customerType: 'company',
    taxId: '300444555666003',
    branch: 'ينبع',
    group: 'تجار الجملة',
    salesRep: 'عبدالله المالكي',
  },
]

export const FILTER_OPTIONS = {
  branches: ['جدة الرئيسي', 'الرياض', 'الدمام', 'مكة', 'ينبع'],
  groups: ['تجار الجملة', 'تجزئة', 'أفراد', 'حكومي'],
  salesReps: ['محمد العتيبي', 'سارة الحربي', 'خالد الشمري', 'فهد القحطاني', 'نورة الزهراني'],
  customerTypes: ['individual', 'company', 'government', 'other'],
  statuses: ['active', 'suspended', 'blocked', 'under_review'],
  creditStatuses: ['within_limit', 'near_limit', 'exceeded'],
  cities: ['جدة', 'الرياض', 'الدمام', 'مكة', 'ينبع'],
} as const
