/**
 * AUTO-GENERATED — do not edit.
 * Regenerate: npm run api:registry
 */
import type { HttpMethod } from '@/api/registry/types'

export interface EndpointRecord {
  method: HttpMethod
  path: string
  tag: string
  summary: string
  auth: boolean
  hasParams: boolean
  ref: string
}

export const API_ENDPOINTS = {
  'accountGroups.create': {
    method: 'POST',
    path: '/AccountGroups',
    tag: 'AccountGroups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/AccountGroups',
  },
  'accountGroups.delete': {
    method: 'DELETE',
    path: '/AccountGroups/{id}',
    tag: 'AccountGroups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/AccountGroups/{id}',
  },
  'accountGroups.getById': {
    method: 'GET',
    path: '/AccountGroups/{id}',
    tag: 'AccountGroups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/AccountGroups/{id}',
  },
  'accountGroups.getByName': {
    method: 'GET',
    path: '/AccountGroups/name/{name}',
    tag: 'AccountGroups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/AccountGroups/name/{name}',
  },
  'accountGroups.list': {
    method: 'GET',
    path: '/AccountGroups',
    tag: 'AccountGroups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/AccountGroups',
  },
  'accountGroups.update': {
    method: 'PUT',
    path: '/AccountGroups/{id}',
    tag: 'AccountGroups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/AccountGroups/{id}',
  },
  'accountingPeriods.close': {
    method: 'POST',
    path: '/AccountingPeriods/{id}/close',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/AccountingPeriods/{id}/close',
  },
  'accountingPeriods.create': {
    method: 'POST',
    path: '/AccountingPeriods',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/AccountingPeriods',
  },
  'accountingPeriods.delete': {
    method: 'DELETE',
    path: '/AccountingPeriods/{id}',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/AccountingPeriods/{id}',
  },
  'accountingPeriods.getByFiscalyear': {
    method: 'GET',
    path: '/AccountingPeriods/fiscalyear/{fiscalYear}',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/AccountingPeriods/fiscalyear/{fiscalYear}',
  },
  'accountingPeriods.getById': {
    method: 'GET',
    path: '/AccountingPeriods/{id}',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/AccountingPeriods/{id}',
  },
  'accountingPeriods.getClosed': {
    method: 'GET',
    path: '/AccountingPeriods/closed',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/AccountingPeriods/closed',
  },
  'accountingPeriods.getCurrent': {
    method: 'GET',
    path: '/AccountingPeriods/current',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/AccountingPeriods/current',
  },
  'accountingPeriods.getOpen': {
    method: 'GET',
    path: '/AccountingPeriods/open',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/AccountingPeriods/open',
  },
  'accountingPeriods.list': {
    method: 'GET',
    path: '/AccountingPeriods',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/AccountingPeriods',
  },
  'accountingPeriods.reopen': {
    method: 'POST',
    path: '/AccountingPeriods/{id}/reopen',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/AccountingPeriods/{id}/reopen',
  },
  'accountingPeriods.update': {
    method: 'PUT',
    path: '/AccountingPeriods/{id}',
    tag: 'AccountingPeriods',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/AccountingPeriods/{id}',
  },
  'accounts.create': {
    method: 'POST',
    path: '/Accounts',
    tag: 'Accounts',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Accounts',
  },
  'accounts.delete': {
    method: 'DELETE',
    path: '/Accounts/{id}',
    tag: 'Accounts',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Accounts/{id}',
  },
  'accounts.getByCode': {
    method: 'GET',
    path: '/Accounts/code/{code}',
    tag: 'Accounts',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Accounts/code/{code}',
  },
  'accounts.getById': {
    method: 'GET',
    path: '/Accounts/{id}',
    tag: 'Accounts',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Accounts/{id}',
  },
  'accounts.getNextCode': {
    method: 'GET',
    path: '/Accounts/next-code',
    tag: 'Accounts',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Accounts/next-code',
  },
  'accounts.list': {
    method: 'GET',
    path: '/Accounts',
    tag: 'Accounts',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Accounts',
  },
  'accounts.lookup': {
    method: 'GET',
    path: '/Accounts/lookup',
    tag: 'Accounts',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Accounts/lookup',
  },
  'accounts.update': {
    method: 'PUT',
    path: '/Accounts/{id}',
    tag: 'Accounts',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Accounts/{id}',
  },
  'auth.login': {
    method: 'POST',
    path: '/Auth/login',
    tag: 'Auth',
    summary: '',
    auth: false,
    hasParams: false,
    ref: 'POST /api/Auth/login',
  },
  'auth.logout': {
    method: 'POST',
    path: '/Auth/logout',
    tag: 'Auth',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Auth/logout',
  },
  'auth.refreshToken': {
    method: 'POST',
    path: '/Auth/refresh-token',
    tag: 'Auth',
    summary: '',
    auth: false,
    hasParams: false,
    ref: 'POST /api/Auth/refresh-token',
  },
  'bankAccounts.create': {
    method: 'POST',
    path: '/BankAccounts',
    tag: 'BankAccounts',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/BankAccounts',
  },
  'bankAccounts.delete': {
    method: 'DELETE',
    path: '/BankAccounts/{id}',
    tag: 'BankAccounts',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/BankAccounts/{id}',
  },
  'bankAccounts.getById': {
    method: 'GET',
    path: '/BankAccounts/{id}',
    tag: 'BankAccounts',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/BankAccounts/{id}',
  },
  'bankAccounts.list': {
    method: 'GET',
    path: '/BankAccounts',
    tag: 'BankAccounts',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/BankAccounts',
  },
  'bankAccounts.toggleStatus': {
    method: 'POST',
    path: '/BankAccounts/{id}/toggle-status',
    tag: 'BankAccounts',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/BankAccounts/{id}/toggle-status',
  },
  'bankAccounts.update': {
    method: 'PUT',
    path: '/BankAccounts/{id}',
    tag: 'BankAccounts',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/BankAccounts/{id}',
  },
  'banks.create': {
    method: 'POST',
    path: '/Banks',
    tag: 'Banks',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Banks',
  },
  'banks.delete': {
    method: 'DELETE',
    path: '/Banks/{id}',
    tag: 'Banks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Banks/{id}',
  },
  'banks.getById': {
    method: 'GET',
    path: '/Banks/{id}',
    tag: 'Banks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Banks/{id}',
  },
  'banks.getById__2': {
    method: 'GET',
    path: '/Banks/{id}/account-count',
    tag: 'Banks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Banks/{id}/account-count',
  },
  'banks.list': {
    method: 'GET',
    path: '/Banks',
    tag: 'Banks',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Banks',
  },
  'banks.toggleStatus': {
    method: 'POST',
    path: '/Banks/{id}/toggle-status',
    tag: 'Banks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/Banks/{id}/toggle-status',
  },
  'banks.update': {
    method: 'PUT',
    path: '/Banks/{id}',
    tag: 'Banks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Banks/{id}',
  },
  'branches.create': {
    method: 'POST',
    path: '/Branches',
    tag: 'Branches',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Branches',
  },
  'branches.delete': {
    method: 'DELETE',
    path: '/Branches/{id}',
    tag: 'Branches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Branches/{id}',
  },
  'branches.getByBranchId': {
    method: 'GET',
    path: '/Branches/branchId/{branchId}',
    tag: 'Branches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Branches/branchId/{branchId}',
  },
  'branches.getByBrand': {
    method: 'GET',
    path: '/Branches/brand/{brandId}',
    tag: 'Branches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Branches/brand/{brandId}',
  },
  'branches.getById': {
    method: 'GET',
    path: '/Branches/{id}',
    tag: 'Branches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Branches/{id}',
  },
  'branches.list': {
    method: 'GET',
    path: '/Branches',
    tag: 'Branches',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Branches',
  },
  'branches.update': {
    method: 'PUT',
    path: '/Branches/{id}',
    tag: 'Branches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Branches/{id}',
  },
  'brands.create': {
    method: 'POST',
    path: '/Brands',
    tag: 'Brands',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Brands',
  },
  'brands.delete': {
    method: 'DELETE',
    path: '/Brands/{id}',
    tag: 'Brands',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Brands/{id}',
  },
  'brands.getByCompany': {
    method: 'GET',
    path: '/Brands/company/{companyId}',
    tag: 'Brands',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Brands/company/{companyId}',
  },
  'brands.getById': {
    method: 'GET',
    path: '/Brands/{id}',
    tag: 'Brands',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Brands/{id}',
  },
  'brands.list': {
    method: 'GET',
    path: '/Brands',
    tag: 'Brands',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Brands',
  },
  'brands.update': {
    method: 'PUT',
    path: '/Brands/{id}',
    tag: 'Brands',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Brands/{id}',
  },
  'checkBooks.create': {
    method: 'POST',
    path: '/CheckBooks',
    tag: 'CheckBooks',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/CheckBooks',
  },
  'checkBooks.delete': {
    method: 'DELETE',
    path: '/CheckBooks/{id}',
    tag: 'CheckBooks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/CheckBooks/{id}',
  },
  'checkBooks.getByBankAccount': {
    method: 'GET',
    path: '/CheckBooks/bank-account/{bankAccountId}',
    tag: 'CheckBooks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/CheckBooks/bank-account/{bankAccountId}',
  },
  'checkBooks.getById': {
    method: 'GET',
    path: '/CheckBooks/{id}',
    tag: 'CheckBooks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/CheckBooks/{id}',
  },
  'checkBooks.getLowStock': {
    method: 'GET',
    path: '/CheckBooks/low-stock',
    tag: 'CheckBooks',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/CheckBooks/low-stock',
  },
  'checkBooks.list': {
    method: 'GET',
    path: '/CheckBooks',
    tag: 'CheckBooks',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/CheckBooks',
  },
  'checkBooks.toggleStatus': {
    method: 'POST',
    path: '/CheckBooks/{id}/toggle-status',
    tag: 'CheckBooks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/CheckBooks/{id}/toggle-status',
  },
  'checkBooks.update': {
    method: 'PUT',
    path: '/CheckBooks/{id}',
    tag: 'CheckBooks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/CheckBooks/{id}',
  },
  'companies.create': {
    method: 'POST',
    path: '/Companies',
    tag: 'Companies',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Companies',
  },
  'companies.delete': {
    method: 'DELETE',
    path: '/Companies/{id}',
    tag: 'Companies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Companies/{id}',
  },
  'companies.getById': {
    method: 'GET',
    path: '/Companies/{id}',
    tag: 'Companies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Companies/{id}',
  },
  'companies.list': {
    method: 'GET',
    path: '/Companies',
    tag: 'Companies',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Companies',
  },
  'companies.update': {
    method: 'PUT',
    path: '/Companies/{id}',
    tag: 'Companies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Companies/{id}',
  },
  'costCenters.create': {
    method: 'POST',
    path: '/CostCenters',
    tag: 'CostCenters',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/CostCenters',
  },
  'costCenters.delete': {
    method: 'DELETE',
    path: '/CostCenters/{id}',
    tag: 'CostCenters',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/CostCenters/{id}',
  },
  'costCenters.getActive': {
    method: 'GET',
    path: '/CostCenters/active',
    tag: 'CostCenters',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/CostCenters/active',
  },
  'costCenters.getByBranch': {
    method: 'GET',
    path: '/CostCenters/branch/{branchId}',
    tag: 'CostCenters',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/CostCenters/branch/{branchId}',
  },
  'costCenters.getByCode': {
    method: 'GET',
    path: '/CostCenters/code/{code}',
    tag: 'CostCenters',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/CostCenters/code/{code}',
  },
  'costCenters.getById': {
    method: 'GET',
    path: '/CostCenters/{id}',
    tag: 'CostCenters',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/CostCenters/{id}',
  },
  'costCenters.getByParent': {
    method: 'GET',
    path: '/CostCenters/parent/{parentId}',
    tag: 'CostCenters',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/CostCenters/parent/{parentId}',
  },
  'costCenters.list': {
    method: 'GET',
    path: '/CostCenters',
    tag: 'CostCenters',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/CostCenters',
  },
  'costCenters.update': {
    method: 'PUT',
    path: '/CostCenters/{id}',
    tag: 'CostCenters',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/CostCenters/{id}',
  },
  'currencies.create': {
    method: 'POST',
    path: '/Currencies',
    tag: 'Currencies',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Currencies',
  },
  'currencies.delete': {
    method: 'DELETE',
    path: '/Currencies/{id}',
    tag: 'Currencies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Currencies/{id}',
  },
  'currencies.getActive': {
    method: 'GET',
    path: '/Currencies/active',
    tag: 'Currencies',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Currencies/active',
  },
  'currencies.getBase': {
    method: 'GET',
    path: '/Currencies/base',
    tag: 'Currencies',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Currencies/base',
  },
  'currencies.getById': {
    method: 'GET',
    path: '/Currencies/{id}',
    tag: 'Currencies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Currencies/{id}',
  },
  'currencies.list': {
    method: 'GET',
    path: '/Currencies',
    tag: 'Currencies',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Currencies',
  },
  'currencies.update': {
    method: 'PUT',
    path: '/Currencies/{id}',
    tag: 'Currencies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Currencies/{id}',
  },
  'customerGroups.create': {
    method: 'POST',
    path: '/CustomerGroups',
    tag: 'CustomerGroups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/CustomerGroups',
  },
  'customerGroups.delete': {
    method: 'DELETE',
    path: '/CustomerGroups/{id}',
    tag: 'CustomerGroups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/CustomerGroups/{id}',
  },
  'customerGroups.getById': {
    method: 'GET',
    path: '/CustomerGroups/{id}',
    tag: 'CustomerGroups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/CustomerGroups/{id}',
  },
  'customerGroups.list': {
    method: 'GET',
    path: '/CustomerGroups',
    tag: 'CustomerGroups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/CustomerGroups',
  },
  'customerGroups.update': {
    method: 'PUT',
    path: '/CustomerGroups/{id}',
    tag: 'CustomerGroups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/CustomerGroups/{id}',
  },
  'customers.create': {
    method: 'POST',
    path: '/Customers',
    tag: 'Customers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Customers',
  },
  'customers.delete': {
    method: 'DELETE',
    path: '/Customers/{id}',
    tag: 'Customers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Customers/{id}',
  },
  'customers.getById': {
    method: 'GET',
    path: '/Customers/{id}',
    tag: 'Customers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Customers/{id}',
  },
  'customers.list': {
    method: 'GET',
    path: '/Customers',
    tag: 'Customers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Customers',
  },
  'customers.update': {
    method: 'PUT',
    path: '/Customers/{id}',
    tag: 'Customers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Customers/{id}',
  },
  'employees.lookup': {
    method: 'GET',
    path: '/Employees/lookup',
    tag: 'Employees',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Employees/lookup',
  },
  'fiscalYears.close': {
    method: 'POST',
    path: '/FiscalYears/{id}/close',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/FiscalYears/{id}/close',
  },
  'fiscalYears.create': {
    method: 'POST',
    path: '/FiscalYears',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/FiscalYears',
  },
  'fiscalYears.delete': {
    method: 'DELETE',
    path: '/FiscalYears/{id}',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/FiscalYears/{id}',
  },
  'fiscalYears.getById': {
    method: 'GET',
    path: '/FiscalYears/{id}',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/FiscalYears/{id}',
  },
  'fiscalYears.getByYear': {
    method: 'GET',
    path: '/FiscalYears/year/{year}',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/FiscalYears/year/{year}',
  },
  'fiscalYears.getClosed': {
    method: 'GET',
    path: '/FiscalYears/closed',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/FiscalYears/closed',
  },
  'fiscalYears.getCurrent': {
    method: 'GET',
    path: '/FiscalYears/current',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/FiscalYears/current',
  },
  'fiscalYears.getOpen': {
    method: 'GET',
    path: '/FiscalYears/open',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/FiscalYears/open',
  },
  'fiscalYears.list': {
    method: 'GET',
    path: '/FiscalYears',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/FiscalYears',
  },
  'fiscalYears.reopen': {
    method: 'POST',
    path: '/FiscalYears/{id}/reopen',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/FiscalYears/{id}/reopen',
  },
  'fiscalYears.update': {
    method: 'PUT',
    path: '/FiscalYears/{id}',
    tag: 'FiscalYears',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/FiscalYears/{id}',
  },
  'generalLedger.getLedger': {
    method: 'GET',
    path: '/GeneralLedger/ledger',
    tag: 'GeneralLedger',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/GeneralLedger/ledger',
  },
  'generalLedger.getTrialBalance': {
    method: 'GET',
    path: '/GeneralLedger/trial-balance',
    tag: 'GeneralLedger',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/GeneralLedger/trial-balance',
  },
  'inventoryReports.create': {
    method: 'POST',
    path: '/reports/inventory/item-movement',
    tag: 'InventoryReports',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/reports/inventory/item-movement',
  },
  'inventoryReports.create__2': {
    method: 'POST',
    path: '/reports/inventory/current-stock',
    tag: 'InventoryReports',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/reports/inventory/current-stock',
  },
  'inventoryReports.create__3': {
    method: 'POST',
    path: '/reports/inventory/stock-issue',
    tag: 'InventoryReports',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/reports/inventory/stock-issue',
  },
  'issuedChecks.approve': {
    method: 'POST',
    path: '/IssuedChecks/{id}/approve',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/IssuedChecks/{id}/approve',
  },
  'issuedChecks.bounce': {
    method: 'POST',
    path: '/IssuedChecks/{id}/bounce',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/IssuedChecks/{id}/bounce',
  },
  'issuedChecks.cancel': {
    method: 'POST',
    path: '/IssuedChecks/{id}/cancel',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/IssuedChecks/{id}/cancel',
  },
  'issuedChecks.create': {
    method: 'POST',
    path: '/IssuedChecks',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/IssuedChecks',
  },
  'issuedChecks.delete': {
    method: 'DELETE',
    path: '/IssuedChecks/{id}',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/IssuedChecks/{id}',
  },
  'issuedChecks.getByBankAccount': {
    method: 'GET',
    path: '/IssuedChecks/bank-account/{bankAccountId}',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/IssuedChecks/bank-account/{bankAccountId}',
  },
  'issuedChecks.getById': {
    method: 'GET',
    path: '/IssuedChecks/{id}',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/IssuedChecks/{id}',
  },
  'issuedChecks.getByStatus': {
    method: 'GET',
    path: '/IssuedChecks/status/{status}',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/IssuedChecks/status/{status}',
  },
  'issuedChecks.getRange': {
    method: 'GET',
    path: '/IssuedChecks/range',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/IssuedChecks/range',
  },
  'issuedChecks.list': {
    method: 'GET',
    path: '/IssuedChecks',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/IssuedChecks',
  },
  'issuedChecks.pay': {
    method: 'POST',
    path: '/IssuedChecks/{id}/pay',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/IssuedChecks/{id}/pay',
  },
  'issuedChecks.post': {
    method: 'POST',
    path: '/IssuedChecks/{id}/post',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/IssuedChecks/{id}/post',
  },
  'issuedChecks.reject': {
    method: 'POST',
    path: '/IssuedChecks/{id}/reject',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/IssuedChecks/{id}/reject',
  },
  'issuedChecks.update': {
    method: 'PUT',
    path: '/IssuedChecks/{id}',
    tag: 'IssuedChecks',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/IssuedChecks/{id}',
  },
  'itemAccountingPolicies.create': {
    method: 'POST',
    path: '/ItemAccountingPolicies',
    tag: 'ItemAccountingPolicies',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/ItemAccountingPolicies',
  },
  'itemAccountingPolicies.delete': {
    method: 'DELETE',
    path: '/ItemAccountingPolicies/{id}',
    tag: 'ItemAccountingPolicies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/ItemAccountingPolicies/{id}',
  },
  'itemAccountingPolicies.delete__2': {
    method: 'DELETE',
    path: '/ItemAccountingPolicies/rules/{ruleId}',
    tag: 'ItemAccountingPolicies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/ItemAccountingPolicies/rules/{ruleId}',
  },
  'itemAccountingPolicies.getById': {
    method: 'GET',
    path: '/ItemAccountingPolicies/{id}',
    tag: 'ItemAccountingPolicies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/ItemAccountingPolicies/{id}',
  },
  'itemAccountingPolicies.getById__2': {
    method: 'GET',
    path: '/ItemAccountingPolicies/{policyId}/rules',
    tag: 'ItemAccountingPolicies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/ItemAccountingPolicies/{policyId}/rules',
  },
  'itemAccountingPolicies.list': {
    method: 'GET',
    path: '/ItemAccountingPolicies',
    tag: 'ItemAccountingPolicies',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/ItemAccountingPolicies',
  },
  'itemAccountingPolicies.rules': {
    method: 'POST',
    path: '/ItemAccountingPolicies/{policyId}/rules',
    tag: 'ItemAccountingPolicies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/ItemAccountingPolicies/{policyId}/rules',
  },
  'itemAccountingPolicies.update': {
    method: 'PUT',
    path: '/ItemAccountingPolicies/{id}',
    tag: 'ItemAccountingPolicies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/ItemAccountingPolicies/{id}',
  },
  'itemAccountingPolicies.update__2': {
    method: 'PUT',
    path: '/ItemAccountingPolicies/rules/{ruleId}',
    tag: 'ItemAccountingPolicies',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/ItemAccountingPolicies/rules/{ruleId}',
  },
  'journalEntries.create': {
    method: 'POST',
    path: '/JournalEntries',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/JournalEntries',
  },
  'journalEntries.create__2': {
    method: 'POST',
    path: '/JournalEntries/post-bulk',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/JournalEntries/post-bulk',
  },
  'journalEntries.delete': {
    method: 'DELETE',
    path: '/JournalEntries/{entryId}',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/JournalEntries/{entryId}',
  },
  'journalEntries.getByBranch': {
    method: 'GET',
    path: '/JournalEntries/branch/{branchId}',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/JournalEntries/branch/{branchId}',
  },
  'journalEntries.getByJournalEntries': {
    method: 'GET',
    path: '/JournalEntries/{entryId}',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/JournalEntries/{entryId}',
  },
  'journalEntries.getByPeriod': {
    method: 'GET',
    path: '/JournalEntries/period/{periodId}',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/JournalEntries/period/{periodId}',
  },
  'journalEntries.getByType': {
    method: 'GET',
    path: '/JournalEntries/type/{journalTypeId}',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/JournalEntries/type/{journalTypeId}',
  },
  'journalEntries.getNextNumber': {
    method: 'GET',
    path: '/JournalEntries/next-number',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/JournalEntries/next-number',
  },
  'journalEntries.getPosted': {
    method: 'GET',
    path: '/JournalEntries/posted',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/JournalEntries/posted',
  },
  'journalEntries.getUnposted': {
    method: 'GET',
    path: '/JournalEntries/unposted',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/JournalEntries/unposted',
  },
  'journalEntries.list': {
    method: 'GET',
    path: '/JournalEntries',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/JournalEntries',
  },
  'journalEntries.post': {
    method: 'POST',
    path: '/JournalEntries/{entryId}/post',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/JournalEntries/{entryId}/post',
  },
  'journalEntries.reverse': {
    method: 'POST',
    path: '/JournalEntries/{entryId}/reverse',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/JournalEntries/{entryId}/reverse',
  },
  'journalEntries.unpost': {
    method: 'POST',
    path: '/JournalEntries/{entryId}/unpost',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/JournalEntries/{entryId}/unpost',
  },
  'journalEntries.update': {
    method: 'PUT',
    path: '/JournalEntries/{entryId}',
    tag: 'JournalEntries',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/JournalEntries/{entryId}',
  },
  'journalTypes.create': {
    method: 'POST',
    path: '/JournalTypes',
    tag: 'JournalTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/JournalTypes',
  },
  'journalTypes.delete': {
    method: 'DELETE',
    path: '/JournalTypes/{id}',
    tag: 'JournalTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/JournalTypes/{id}',
  },
  'journalTypes.getActive': {
    method: 'GET',
    path: '/JournalTypes/active',
    tag: 'JournalTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/JournalTypes/active',
  },
  'journalTypes.getByCode': {
    method: 'GET',
    path: '/JournalTypes/code/{code}',
    tag: 'JournalTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/JournalTypes/code/{code}',
  },
  'journalTypes.getById': {
    method: 'GET',
    path: '/JournalTypes/{id}',
    tag: 'JournalTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/JournalTypes/{id}',
  },
  'journalTypes.list': {
    method: 'GET',
    path: '/JournalTypes',
    tag: 'JournalTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/JournalTypes',
  },
  'journalTypes.update': {
    method: 'PUT',
    path: '/JournalTypes/{id}',
    tag: 'JournalTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/JournalTypes/{id}',
  },
  'lookups.customers': {
    method: 'GET',
    path: '/Lookups/customers',
    tag: 'Lookups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Lookups/customers',
  },
  'lookups.documentStatuses': {
    method: 'GET',
    path: '/Lookups/document-statuses',
    tag: 'Lookups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Lookups/document-statuses',
  },
  'lookups.partnerTypes': {
    method: 'GET',
    path: '/Lookups/partner-types',
    tag: 'Lookups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Lookups/partner-types',
  },
  'lookups.products': {
    method: 'GET',
    path: '/Lookups/products',
    tag: 'Lookups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Lookups/products',
  },
  'lookups.suppliers': {
    method: 'GET',
    path: '/Lookups/suppliers',
    tag: 'Lookups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Lookups/suppliers',
  },
  'modules.create': {
    method: 'POST',
    path: '/Modules',
    tag: 'Modules',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Modules',
  },
  'modules.delete': {
    method: 'DELETE',
    path: '/Modules/{id}',
    tag: 'Modules',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Modules/{id}',
  },
  'modules.getById': {
    method: 'GET',
    path: '/Modules/{id}',
    tag: 'Modules',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Modules/{id}',
  },
  'modules.getById__2': {
    method: 'GET',
    path: '/Modules/{id}/submodules',
    tag: 'Modules',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Modules/{id}/submodules',
  },
  'modules.getByKey': {
    method: 'GET',
    path: '/Modules/key/{key}',
    tag: 'Modules',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Modules/key/{key}',
  },
  'modules.getRoot': {
    method: 'GET',
    path: '/Modules/root',
    tag: 'Modules',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Modules/root',
  },
  'modules.getTree': {
    method: 'GET',
    path: '/Modules/tree',
    tag: 'Modules',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Modules/tree',
  },
  'modules.list': {
    method: 'GET',
    path: '/Modules',
    tag: 'Modules',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Modules',
  },
  'modules.update': {
    method: 'PUT',
    path: '/Modules/{id}',
    tag: 'Modules',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Modules/{id}',
  },
  'openingBalances.create': {
    method: 'POST',
    path: '/OpeningBalances',
    tag: 'OpeningBalances',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/OpeningBalances',
  },
  'openingBalances.delete': {
    method: 'DELETE',
    path: '/OpeningBalances/{id}',
    tag: 'OpeningBalances',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/OpeningBalances/{id}',
  },
  'openingBalances.getById': {
    method: 'GET',
    path: '/OpeningBalances/{id}',
    tag: 'OpeningBalances',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/OpeningBalances/{id}',
  },
  'openingBalances.list': {
    method: 'GET',
    path: '/OpeningBalances',
    tag: 'OpeningBalances',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/OpeningBalances',
  },
  'openingBalances.post': {
    method: 'POST',
    path: '/OpeningBalances/{id}/post',
    tag: 'OpeningBalances',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/OpeningBalances/{id}/post',
  },
  'openingBalances.update': {
    method: 'PUT',
    path: '/OpeningBalances/{id}',
    tag: 'OpeningBalances',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/OpeningBalances/{id}',
  },
  'paymentTypes.create': {
    method: 'POST',
    path: '/PaymentTypes',
    tag: 'PaymentTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/PaymentTypes',
  },
  'paymentTypes.delete': {
    method: 'DELETE',
    path: '/PaymentTypes/{id}',
    tag: 'PaymentTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/PaymentTypes/{id}',
  },
  'paymentTypes.getById': {
    method: 'GET',
    path: '/PaymentTypes/{id}',
    tag: 'PaymentTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/PaymentTypes/{id}',
  },
  'paymentTypes.list': {
    method: 'GET',
    path: '/PaymentTypes',
    tag: 'PaymentTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/PaymentTypes',
  },
  'paymentTypes.update': {
    method: 'PUT',
    path: '/PaymentTypes/{id}',
    tag: 'PaymentTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/PaymentTypes/{id}',
  },
  'paymentVouchers.approve': {
    method: 'POST',
    path: '/PaymentVouchers/{id}/approve',
    tag: 'PaymentVouchers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/PaymentVouchers/{id}/approve',
  },
  'paymentVouchers.create': {
    method: 'POST',
    path: '/PaymentVouchers',
    tag: 'PaymentVouchers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/PaymentVouchers',
  },
  'paymentVouchers.delete': {
    method: 'DELETE',
    path: '/PaymentVouchers/{id}',
    tag: 'PaymentVouchers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/PaymentVouchers/{id}',
  },
  'paymentVouchers.getById': {
    method: 'GET',
    path: '/PaymentVouchers/{id}',
    tag: 'PaymentVouchers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/PaymentVouchers/{id}',
  },
  'paymentVouchers.getNextNumber': {
    method: 'GET',
    path: '/PaymentVouchers/next-number',
    tag: 'PaymentVouchers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/PaymentVouchers/next-number',
  },
  'paymentVouchers.list': {
    method: 'GET',
    path: '/PaymentVouchers',
    tag: 'PaymentVouchers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/PaymentVouchers',
  },
  'paymentVouchers.update': {
    method: 'PUT',
    path: '/PaymentVouchers/{id}',
    tag: 'PaymentVouchers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/PaymentVouchers/{id}',
  },
  'permissionAuditLog.getById': {
    method: 'GET',
    path: '/PermissionAuditLog/entity/{entityType}/{entityId}',
    tag: 'PermissionAuditLog',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/PermissionAuditLog/entity/{entityType}/{entityId}',
  },
  'permissionAuditLog.getByModule': {
    method: 'GET',
    path: '/PermissionAuditLog/module/{moduleId}',
    tag: 'PermissionAuditLog',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/PermissionAuditLog/module/{moduleId}',
  },
  'permissionAuditLog.getByUser': {
    method: 'GET',
    path: '/PermissionAuditLog/user/{userId}',
    tag: 'PermissionAuditLog',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/PermissionAuditLog/user/{userId}',
  },
  'permissionAuditLog.getCount': {
    method: 'GET',
    path: '/PermissionAuditLog/count',
    tag: 'PermissionAuditLog',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/PermissionAuditLog/count',
  },
  'permissionAuditLog.list': {
    method: 'GET',
    path: '/PermissionAuditLog',
    tag: 'PermissionAuditLog',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/PermissionAuditLog',
  },
  'permissions.create': {
    method: 'POST',
    path: '/Permissions/roles/set',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Permissions/roles/set',
  },
  'permissions.create__2': {
    method: 'POST',
    path: '/Permissions/roles/set-bulk',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Permissions/roles/set-bulk',
  },
  'permissions.create__3': {
    method: 'POST',
    path: '/Permissions/users/check',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Permissions/users/check',
  },
  'permissions.create__4': {
    method: 'POST',
    path: '/Permissions/users/overrides/set',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Permissions/users/overrides/set',
  },
  'permissions.create__5': {
    method: 'POST',
    path: '/Permissions/users/overrides/set-bulk',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Permissions/users/overrides/set-bulk',
  },
  'permissions.create__6': {
    method: 'POST',
    path: '/Permissions/users/copy',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Permissions/users/copy',
  },
  'permissions.getByBranches': {
    method: 'GET',
    path: '/Permissions/users/{userId}/branches/{branchId}',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Permissions/users/{userId}/branches/{branchId}',
  },
  'permissions.getById': {
    method: 'GET',
    path: '/Permissions/{id}',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Permissions/{id}',
  },
  'permissions.getById__2': {
    method: 'GET',
    path: '/Permissions/roles/{roleId}/matrix',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Permissions/roles/{roleId}/matrix',
  },
  'permissions.getById__3': {
    method: 'GET',
    path: '/Permissions/users/{userId}/overrides',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Permissions/users/{userId}/overrides',
  },
  'permissions.getByKey': {
    method: 'GET',
    path: '/Permissions/key/{key}',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Permissions/key/{key}',
  },
  'permissions.getByUsers': {
    method: 'GET',
    path: '/Permissions/users/{userId}',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Permissions/users/{userId}',
  },
  'permissions.list': {
    method: 'GET',
    path: '/Permissions',
    tag: 'Permissions',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Permissions',
  },
  'pricing.create': {
    method: 'POST',
    path: '/Pricing/price-lists',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Pricing/price-lists',
  },
  'pricing.create__2': {
    method: 'POST',
    path: '/Pricing/branch-assignments',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Pricing/branch-assignments',
  },
  'pricing.create__3': {
    method: 'POST',
    path: '/Pricing/update-price',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Pricing/update-price',
  },
  'pricing.create__4': {
    method: 'POST',
    path: '/Pricing/bulk-update',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Pricing/bulk-update',
  },
  'pricing.create__5': {
    method: 'POST',
    path: '/Pricing/change-log',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Pricing/change-log',
  },
  'pricing.delete': {
    method: 'DELETE',
    path: '/Pricing/price-lists/{id}',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Pricing/price-lists/{id}',
  },
  'pricing.delete__2': {
    method: 'DELETE',
    path: '/Pricing/branch-assignments/{id}',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Pricing/branch-assignments/{id}',
  },
  'pricing.getBranchAssignments': {
    method: 'GET',
    path: '/Pricing/branch-assignments',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Pricing/branch-assignments',
  },
  'pricing.getById': {
    method: 'GET',
    path: '/Pricing/price-lists/{id}',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Pricing/price-lists/{id}',
  },
  'pricing.getById__2': {
    method: 'GET',
    path: '/Pricing/branch-assignments/{id}',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Pricing/branch-assignments/{id}',
  },
  'pricing.getDashboard': {
    method: 'GET',
    path: '/Pricing/dashboard',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Pricing/dashboard',
  },
  'pricing.getPriceLists': {
    method: 'GET',
    path: '/Pricing/price-lists',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Pricing/price-lists',
  },
  'pricing.update': {
    method: 'PUT',
    path: '/Pricing/price-lists/{id}',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Pricing/price-lists/{id}',
  },
  'pricing.update__2': {
    method: 'PUT',
    path: '/Pricing/branch-assignments/{id}',
    tag: 'Pricing',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Pricing/branch-assignments/{id}',
  },
  'productAlternatives.create': {
    method: 'POST',
    path: '/ProductAlternatives',
    tag: 'ProductAlternatives',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/ProductAlternatives',
  },
  'productAlternatives.delete': {
    method: 'DELETE',
    path: '/ProductAlternatives/{id}',
    tag: 'ProductAlternatives',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/ProductAlternatives/{id}',
  },
  'productAlternatives.getById': {
    method: 'GET',
    path: '/ProductAlternatives/{id}',
    tag: 'ProductAlternatives',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/ProductAlternatives/{id}',
  },
  'productAlternatives.getByProduct': {
    method: 'GET',
    path: '/ProductAlternatives/product/{productId}',
    tag: 'ProductAlternatives',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/ProductAlternatives/product/{productId}',
  },
  'productAlternatives.list': {
    method: 'GET',
    path: '/ProductAlternatives',
    tag: 'ProductAlternatives',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/ProductAlternatives',
  },
  'productAlternatives.toggleActive': {
    method: 'POST',
    path: '/ProductAlternatives/{id}/toggle-active',
    tag: 'ProductAlternatives',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/ProductAlternatives/{id}/toggle-active',
  },
  'productAlternatives.update': {
    method: 'PUT',
    path: '/ProductAlternatives/{id}',
    tag: 'ProductAlternatives',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/ProductAlternatives/{id}',
  },
  'products.create': {
    method: 'POST',
    path: '/Products',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Products',
  },
  'products.create__2': {
    method: 'POST',
    path: '/Products/upload-image',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Products/upload-image',
  },
  'products.delete': {
    method: 'DELETE',
    path: '/Products/{id}',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Products/{id}',
  },
  'products.getAccountMapping': {
    method: 'GET',
    path: '/Products/account-mapping',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Products/account-mapping',
  },
  'products.getById': {
    method: 'GET',
    path: '/Products/{id}',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Products/{id}',
  },
  'products.getById__2': {
    method: 'GET',
    path: '/Products/{id}/details',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Products/{id}/details',
  },
  'products.getById__3': {
    method: 'GET',
    path: '/Products/{id}/units',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Products/{id}/units',
  },
  'products.getById__4': {
    method: 'GET',
    path: '/Products/{id}/images',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Products/{id}/images',
  },
  'products.getById__5': {
    method: 'GET',
    path: '/Products/{id}/components',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Products/{id}/components',
  },
  'products.list': {
    method: 'GET',
    path: '/Products',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Products',
  },
  'products.search': {
    method: 'GET',
    path: '/Products/search',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Products/search',
  },
  'products.toggleStatus': {
    method: 'PATCH',
    path: '/Products/{id}/toggle-status',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PATCH /api/Products/{id}/toggle-status',
  },
  'products.update': {
    method: 'PUT',
    path: '/Products/{id}',
    tag: 'Products',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Products/{id}',
  },
  'productsGroups.create': {
    method: 'POST',
    path: '/ProductsGroups',
    tag: 'ProductsGroups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/ProductsGroups',
  },
  'productsGroups.delete': {
    method: 'DELETE',
    path: '/ProductsGroups/{id}',
    tag: 'ProductsGroups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/ProductsGroups/{id}',
  },
  'productsGroups.getById': {
    method: 'GET',
    path: '/ProductsGroups/{id}',
    tag: 'ProductsGroups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/ProductsGroups/{id}',
  },
  'productsGroups.list': {
    method: 'GET',
    path: '/ProductsGroups',
    tag: 'ProductsGroups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/ProductsGroups',
  },
  'productsGroups.update': {
    method: 'PUT',
    path: '/ProductsGroups/{id}',
    tag: 'ProductsGroups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/ProductsGroups/{id}',
  },
  'receiptVouchers.approve': {
    method: 'POST',
    path: '/ReceiptVouchers/{id}/approve',
    tag: 'ReceiptVouchers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/ReceiptVouchers/{id}/approve',
  },
  'receiptVouchers.create': {
    method: 'POST',
    path: '/ReceiptVouchers',
    tag: 'ReceiptVouchers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/ReceiptVouchers',
  },
  'receiptVouchers.delete': {
    method: 'DELETE',
    path: '/ReceiptVouchers/{id}',
    tag: 'ReceiptVouchers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/ReceiptVouchers/{id}',
  },
  'receiptVouchers.getById': {
    method: 'GET',
    path: '/ReceiptVouchers/{id}',
    tag: 'ReceiptVouchers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/ReceiptVouchers/{id}',
  },
  'receiptVouchers.getNextNumber': {
    method: 'GET',
    path: '/ReceiptVouchers/next-number',
    tag: 'ReceiptVouchers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/ReceiptVouchers/next-number',
  },
  'receiptVouchers.list': {
    method: 'GET',
    path: '/ReceiptVouchers',
    tag: 'ReceiptVouchers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/ReceiptVouchers',
  },
  'receiptVouchers.update': {
    method: 'PUT',
    path: '/ReceiptVouchers/{id}',
    tag: 'ReceiptVouchers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/ReceiptVouchers/{id}',
  },
  'referenceTypes.create': {
    method: 'POST',
    path: '/ReferenceTypes',
    tag: 'ReferenceTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/ReferenceTypes',
  },
  'referenceTypes.delete': {
    method: 'DELETE',
    path: '/ReferenceTypes/{id}',
    tag: 'ReferenceTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/ReferenceTypes/{id}',
  },
  'referenceTypes.getById': {
    method: 'GET',
    path: '/ReferenceTypes/{id}',
    tag: 'ReferenceTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/ReferenceTypes/{id}',
  },
  'referenceTypes.list': {
    method: 'GET',
    path: '/ReferenceTypes',
    tag: 'ReferenceTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/ReferenceTypes',
  },
  'referenceTypes.update': {
    method: 'PUT',
    path: '/ReferenceTypes/{id}',
    tag: 'ReferenceTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/ReferenceTypes/{id}',
  },
  'roles.create': {
    method: 'POST',
    path: '/Roles',
    tag: 'Roles',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Roles',
  },
  'roles.delete': {
    method: 'DELETE',
    path: '/Roles/{id}',
    tag: 'Roles',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Roles/{id}',
  },
  'roles.getById': {
    method: 'GET',
    path: '/Roles/{id}',
    tag: 'Roles',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Roles/{id}',
  },
  'roles.getByName': {
    method: 'GET',
    path: '/Roles/name/{name}',
    tag: 'Roles',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Roles/name/{name}',
  },
  'roles.list': {
    method: 'GET',
    path: '/Roles',
    tag: 'Roles',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Roles',
  },
  'roles.update': {
    method: 'PUT',
    path: '/Roles/{id}',
    tag: 'Roles',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Roles/{id}',
  },
  'salesInvoice.cancel': {
    method: 'POST',
    path: '/SalesInvoice/{id}/cancel',
    tag: 'SalesInvoice',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/SalesInvoice/{id}/cancel',
  },
  'salesInvoice.create': {
    method: 'POST',
    path: '/SalesInvoice',
    tag: 'SalesInvoice',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/SalesInvoice',
  },
  'salesInvoice.getById': {
    method: 'GET',
    path: '/SalesInvoice/{id}',
    tag: 'SalesInvoice',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/SalesInvoice/{id}',
  },
  'salesInvoice.getDrafts': {
    method: 'GET',
    path: '/SalesInvoice/drafts',
    tag: 'SalesInvoice',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/SalesInvoice/drafts',
  },
  'salesInvoice.getNextNumber': {
    method: 'GET',
    path: '/SalesInvoice/next-number',
    tag: 'SalesInvoice',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/SalesInvoice/next-number',
  },
  'salesInvoice.list': {
    method: 'GET',
    path: '/SalesInvoice',
    tag: 'SalesInvoice',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/SalesInvoice',
  },
  'salesInvoice.post': {
    method: 'POST',
    path: '/SalesInvoice/{id}/post',
    tag: 'SalesInvoice',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/SalesInvoice/{id}/post',
  },
  'salesmen.create': {
    method: 'POST',
    path: '/Salesmen',
    tag: 'Salesmen',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Salesmen',
  },
  'salesmen.delete': {
    method: 'DELETE',
    path: '/Salesmen/{id}',
    tag: 'Salesmen',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Salesmen/{id}',
  },
  'salesmen.getById': {
    method: 'GET',
    path: '/Salesmen/{id}',
    tag: 'Salesmen',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Salesmen/{id}',
  },
  'salesmen.list': {
    method: 'GET',
    path: '/Salesmen',
    tag: 'Salesmen',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Salesmen',
  },
  'salesmen.update': {
    method: 'PUT',
    path: '/Salesmen/{id}',
    tag: 'Salesmen',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Salesmen/{id}',
  },
  'stockAdjustment.create': {
    method: 'POST',
    path: '/StockAdjustment',
    tag: 'StockAdjustment',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/StockAdjustment',
  },
  'stockAdjustment.getById': {
    method: 'GET',
    path: '/StockAdjustment/{id}',
    tag: 'StockAdjustment',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockAdjustment/{id}',
  },
  'stockAdjustment.getByItemsFromTaking': {
    method: 'GET',
    path: '/StockAdjustment/items-from-taking/{takingId}',
    tag: 'StockAdjustment',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockAdjustment/items-from-taking/{takingId}',
  },
  'stockAdjustment.getDrafts': {
    method: 'GET',
    path: '/StockAdjustment/drafts',
    tag: 'StockAdjustment',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockAdjustment/drafts',
  },
  'stockAdjustment.getNextNumber': {
    method: 'GET',
    path: '/StockAdjustment/next-number',
    tag: 'StockAdjustment',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockAdjustment/next-number',
  },
  'stockAdjustment.list': {
    method: 'GET',
    path: '/StockAdjustment',
    tag: 'StockAdjustment',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockAdjustment',
  },
  'stockAdjustment.post': {
    method: 'POST',
    path: '/StockAdjustment/{id}/post',
    tag: 'StockAdjustment',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/StockAdjustment/{id}/post',
  },
  'stockIssue.create': {
    method: 'POST',
    path: '/StockIssue',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/StockIssue',
  },
  'stockIssue.delete': {
    method: 'DELETE',
    path: '/StockIssue/{id}',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/StockIssue/{id}',
  },
  'stockIssue.getAvailableQty': {
    method: 'GET',
    path: '/StockIssue/available-qty',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockIssue/available-qty',
  },
  'stockIssue.getByBarcode': {
    method: 'GET',
    path: '/StockIssue/barcode/{barcode}',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockIssue/barcode/{barcode}',
  },
  'stockIssue.getByExchangeRate': {
    method: 'GET',
    path: '/StockIssue/exchange-rate/{currencyId}',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockIssue/exchange-rate/{currencyId}',
  },
  'stockIssue.getById': {
    method: 'GET',
    path: '/StockIssue/{id}',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockIssue/{id}',
  },
  'stockIssue.getByItemUnits': {
    method: 'GET',
    path: '/StockIssue/item-units/{itemId}',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockIssue/item-units/{itemId}',
  },
  'stockIssue.getNextNumber': {
    method: 'GET',
    path: '/StockIssue/next-number',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockIssue/next-number',
  },
  'stockIssue.getPending': {
    method: 'GET',
    path: '/StockIssue/pending',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockIssue/pending',
  },
  'stockIssue.list': {
    method: 'GET',
    path: '/StockIssue',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockIssue',
  },
  'stockIssue.post': {
    method: 'POST',
    path: '/StockIssue/{id}/post',
    tag: 'StockIssue',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/StockIssue/{id}/post',
  },
  'stockIssueTypes.create': {
    method: 'POST',
    path: '/StockIssueTypes',
    tag: 'StockIssueTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/StockIssueTypes',
  },
  'stockIssueTypes.delete': {
    method: 'DELETE',
    path: '/StockIssueTypes/{id}',
    tag: 'StockIssueTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/StockIssueTypes/{id}',
  },
  'stockIssueTypes.getById': {
    method: 'GET',
    path: '/StockIssueTypes/{id}',
    tag: 'StockIssueTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockIssueTypes/{id}',
  },
  'stockIssueTypes.list': {
    method: 'GET',
    path: '/StockIssueTypes',
    tag: 'StockIssueTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockIssueTypes',
  },
  'stockIssueTypes.update': {
    method: 'PUT',
    path: '/StockIssueTypes/{id}',
    tag: 'StockIssueTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/StockIssueTypes/{id}',
  },
  'stockReceiving.create': {
    method: 'POST',
    path: '/StockReceiving',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/StockReceiving',
  },
  'stockReceiving.delete': {
    method: 'DELETE',
    path: '/StockReceiving/{id}',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/StockReceiving/{id}',
  },
  'stockReceiving.getAvailableQty': {
    method: 'GET',
    path: '/StockReceiving/available-qty',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockReceiving/available-qty',
  },
  'stockReceiving.getByBarcode': {
    method: 'GET',
    path: '/StockReceiving/barcode/{barcode}',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockReceiving/barcode/{barcode}',
  },
  'stockReceiving.getByExchangeRate': {
    method: 'GET',
    path: '/StockReceiving/exchange-rate/{currencyId}',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockReceiving/exchange-rate/{currencyId}',
  },
  'stockReceiving.getById': {
    method: 'GET',
    path: '/StockReceiving/{id}',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockReceiving/{id}',
  },
  'stockReceiving.getByItemUnits': {
    method: 'GET',
    path: '/StockReceiving/item-units/{itemId}',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockReceiving/item-units/{itemId}',
  },
  'stockReceiving.getNextNumber': {
    method: 'GET',
    path: '/StockReceiving/next-number',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockReceiving/next-number',
  },
  'stockReceiving.getPending': {
    method: 'GET',
    path: '/StockReceiving/pending',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockReceiving/pending',
  },
  'stockReceiving.list': {
    method: 'GET',
    path: '/StockReceiving',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockReceiving',
  },
  'stockReceiving.post': {
    method: 'POST',
    path: '/StockReceiving/{id}/post',
    tag: 'StockReceiving',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/StockReceiving/{id}/post',
  },
  'stockReceivingTypes.create': {
    method: 'POST',
    path: '/StockReceivingTypes',
    tag: 'StockReceivingTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/StockReceivingTypes',
  },
  'stockReceivingTypes.delete': {
    method: 'DELETE',
    path: '/StockReceivingTypes/{id}',
    tag: 'StockReceivingTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/StockReceivingTypes/{id}',
  },
  'stockReceivingTypes.getById': {
    method: 'GET',
    path: '/StockReceivingTypes/{id}',
    tag: 'StockReceivingTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockReceivingTypes/{id}',
  },
  'stockReceivingTypes.list': {
    method: 'GET',
    path: '/StockReceivingTypes',
    tag: 'StockReceivingTypes',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockReceivingTypes',
  },
  'stockReceivingTypes.update': {
    method: 'PUT',
    path: '/StockReceivingTypes/{id}',
    tag: 'StockReceivingTypes',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/StockReceivingTypes/{id}',
  },
  'stockTaking.cancel': {
    method: 'POST',
    path: '/StockTaking/{id}/cancel',
    tag: 'StockTaking',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/StockTaking/{id}/cancel',
  },
  'stockTaking.create': {
    method: 'POST',
    path: '/StockTaking',
    tag: 'StockTaking',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/StockTaking',
  },
  'stockTaking.getAvailableForAdjustment': {
    method: 'GET',
    path: '/StockTaking/available-for-adjustment',
    tag: 'StockTaking',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockTaking/available-for-adjustment',
  },
  'stockTaking.getById': {
    method: 'GET',
    path: '/StockTaking/{id}',
    tag: 'StockTaking',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockTaking/{id}',
  },
  'stockTaking.getByStoreItems': {
    method: 'GET',
    path: '/StockTaking/store-items/{storeId}',
    tag: 'StockTaking',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockTaking/store-items/{storeId}',
  },
  'stockTaking.getDrafts': {
    method: 'GET',
    path: '/StockTaking/drafts',
    tag: 'StockTaking',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockTaking/drafts',
  },
  'stockTaking.getNextNumber': {
    method: 'GET',
    path: '/StockTaking/next-number',
    tag: 'StockTaking',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockTaking/next-number',
  },
  'stockTaking.list': {
    method: 'GET',
    path: '/StockTaking',
    tag: 'StockTaking',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockTaking',
  },
  'stockTaking.post': {
    method: 'POST',
    path: '/StockTaking/{id}/post',
    tag: 'StockTaking',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/StockTaking/{id}/post',
  },
  'stockTaking.search': {
    method: 'POST',
    path: '/StockTaking/search',
    tag: 'StockTaking',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/StockTaking/search',
  },
  'stockTransfer.create': {
    method: 'POST',
    path: '/StockTransfer',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/StockTransfer',
  },
  'stockTransfer.delete': {
    method: 'DELETE',
    path: '/StockTransfer/{id}',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/StockTransfer/{id}',
  },
  'stockTransfer.getAvailableQty': {
    method: 'GET',
    path: '/StockTransfer/available-qty',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockTransfer/available-qty',
  },
  'stockTransfer.getByBarcode': {
    method: 'GET',
    path: '/StockTransfer/barcode/{barcode}',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockTransfer/barcode/{barcode}',
  },
  'stockTransfer.getByExchangeRate': {
    method: 'GET',
    path: '/StockTransfer/exchange-rate/{currencyId}',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockTransfer/exchange-rate/{currencyId}',
  },
  'stockTransfer.getById': {
    method: 'GET',
    path: '/StockTransfer/{id}',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockTransfer/{id}',
  },
  'stockTransfer.getByItemUnits': {
    method: 'GET',
    path: '/StockTransfer/item-units/{itemId}',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/StockTransfer/item-units/{itemId}',
  },
  'stockTransfer.getNextNumber': {
    method: 'GET',
    path: '/StockTransfer/next-number',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockTransfer/next-number',
  },
  'stockTransfer.getPending': {
    method: 'GET',
    path: '/StockTransfer/pending',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockTransfer/pending',
  },
  'stockTransfer.list': {
    method: 'GET',
    path: '/StockTransfer',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/StockTransfer',
  },
  'stockTransfer.post': {
    method: 'POST',
    path: '/StockTransfer/{id}/post',
    tag: 'StockTransfer',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/StockTransfer/{id}/post',
  },
  'stores.create': {
    method: 'POST',
    path: '/Stores',
    tag: 'Stores',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Stores',
  },
  'stores.delete': {
    method: 'DELETE',
    path: '/Stores/{id}',
    tag: 'Stores',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Stores/{id}',
  },
  'stores.getByBranch': {
    method: 'GET',
    path: '/Stores/branch/{branchId}',
    tag: 'Stores',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Stores/branch/{branchId}',
  },
  'stores.getById': {
    method: 'GET',
    path: '/Stores/{id}',
    tag: 'Stores',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Stores/{id}',
  },
  'stores.list': {
    method: 'GET',
    path: '/Stores',
    tag: 'Stores',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Stores',
  },
  'stores.update': {
    method: 'PUT',
    path: '/Stores/{id}',
    tag: 'Stores',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Stores/{id}',
  },
  'suppliers.create': {
    method: 'POST',
    path: '/Suppliers',
    tag: 'Suppliers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Suppliers',
  },
  'suppliers.delete': {
    method: 'DELETE',
    path: '/Suppliers/{id}',
    tag: 'Suppliers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Suppliers/{id}',
  },
  'suppliers.getActive': {
    method: 'GET',
    path: '/Suppliers/active',
    tag: 'Suppliers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Suppliers/active',
  },
  'suppliers.getById': {
    method: 'GET',
    path: '/Suppliers/{id}',
    tag: 'Suppliers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Suppliers/{id}',
  },
  'suppliers.list': {
    method: 'GET',
    path: '/Suppliers',
    tag: 'Suppliers',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Suppliers',
  },
  'suppliers.toggleStatus': {
    method: 'POST',
    path: '/Suppliers/{id}/toggle-status',
    tag: 'Suppliers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'POST /api/Suppliers/{id}/toggle-status',
  },
  'suppliers.update': {
    method: 'PUT',
    path: '/Suppliers/{id}',
    tag: 'Suppliers',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Suppliers/{id}',
  },
  'systemAuditLog.getById': {
    method: 'GET',
    path: '/SystemAuditLog/{id}',
    tag: 'SystemAuditLog',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/SystemAuditLog/{id}',
  },
  'systemAuditLog.list': {
    method: 'GET',
    path: '/SystemAuditLog',
    tag: 'SystemAuditLog',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/SystemAuditLog',
  },
  'systemLog.create': {
    method: 'POST',
    path: '/SystemLog',
    tag: 'SystemLog',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/SystemLog',
  },
  'systemLog.getById': {
    method: 'GET',
    path: '/SystemLog/{id}',
    tag: 'SystemLog',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/SystemLog/{id}',
  },
  'systemLog.list': {
    method: 'GET',
    path: '/SystemLog',
    tag: 'SystemLog',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/SystemLog',
  },
  'taxSetups.create': {
    method: 'POST',
    path: '/TaxSetups',
    tag: 'TaxSetups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/TaxSetups',
  },
  'taxSetups.delete': {
    method: 'DELETE',
    path: '/TaxSetups/{id}',
    tag: 'TaxSetups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/TaxSetups/{id}',
  },
  'taxSetups.getActive': {
    method: 'GET',
    path: '/TaxSetups/active',
    tag: 'TaxSetups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/TaxSetups/active',
  },
  'taxSetups.getByAccount': {
    method: 'GET',
    path: '/TaxSetups/account/{accountId}',
    tag: 'TaxSetups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/TaxSetups/account/{accountId}',
  },
  'taxSetups.getByCode': {
    method: 'GET',
    path: '/TaxSetups/code/{code}',
    tag: 'TaxSetups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/TaxSetups/code/{code}',
  },
  'taxSetups.getById': {
    method: 'GET',
    path: '/TaxSetups/{id}',
    tag: 'TaxSetups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/TaxSetups/{id}',
  },
  'taxSetups.getByType': {
    method: 'GET',
    path: '/TaxSetups/type/{taxType}',
    tag: 'TaxSetups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/TaxSetups/type/{taxType}',
  },
  'taxSetups.list': {
    method: 'GET',
    path: '/TaxSetups',
    tag: 'TaxSetups',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/TaxSetups',
  },
  'taxSetups.update': {
    method: 'PUT',
    path: '/TaxSetups/{id}',
    tag: 'TaxSetups',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/TaxSetups/{id}',
  },
  'units.create': {
    method: 'POST',
    path: '/Units',
    tag: 'Units',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Units',
  },
  'units.delete': {
    method: 'DELETE',
    path: '/Units/{id}',
    tag: 'Units',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Units/{id}',
  },
  'units.getById': {
    method: 'GET',
    path: '/Units/{id}',
    tag: 'Units',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Units/{id}',
  },
  'units.list': {
    method: 'GET',
    path: '/Units',
    tag: 'Units',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Units',
  },
  'units.update': {
    method: 'PUT',
    path: '/Units/{id}',
    tag: 'Units',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Units/{id}',
  },
  'userBranches.create': {
    method: 'POST',
    path: '/UserBranches',
    tag: 'UserBranches',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/UserBranches',
  },
  'userBranches.create__2': {
    method: 'POST',
    path: '/UserBranches/assign',
    tag: 'UserBranches',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/UserBranches/assign',
  },
  'userBranches.delete': {
    method: 'DELETE',
    path: '/UserBranches/{id}',
    tag: 'UserBranches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/UserBranches/{id}',
  },
  'userBranches.getByBranches': {
    method: 'GET',
    path: '/UserBranches/branches/{branchId}',
    tag: 'UserBranches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/UserBranches/branches/{branchId}',
  },
  'userBranches.getByBranches__2': {
    method: 'GET',
    path: '/UserBranches/users/{userId}/branches/{branchId}',
    tag: 'UserBranches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/UserBranches/users/{userId}/branches/{branchId}',
  },
  'userBranches.getById': {
    method: 'GET',
    path: '/UserBranches/users/{userId}/default',
    tag: 'UserBranches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/UserBranches/users/{userId}/default',
  },
  'userBranches.getByUsers': {
    method: 'GET',
    path: '/UserBranches/users/{userId}',
    tag: 'UserBranches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/UserBranches/users/{userId}',
  },
  'userBranches.setDefault': {
    method: 'PUT',
    path: '/UserBranches/users/{userId}/branches/{branchId}/set-default',
    tag: 'UserBranches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/UserBranches/users/{userId}/branches/{branchId}/set-default',
  },
  'userBranches.update': {
    method: 'PUT',
    path: '/UserBranches/{id}',
    tag: 'UserBranches',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/UserBranches/{id}',
  },
  'users.create': {
    method: 'POST',
    path: '/Users',
    tag: 'Users',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'POST /api/Users',
  },
  'users.delete': {
    method: 'DELETE',
    path: '/Users/{id}',
    tag: 'Users',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'DELETE /api/Users/{id}',
  },
  'users.getById': {
    method: 'GET',
    path: '/Users/{id}',
    tag: 'Users',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'GET /api/Users/{id}',
  },
  'users.list': {
    method: 'GET',
    path: '/Users',
    tag: 'Users',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /api/Users',
  },
  'users.update': {
    method: 'PUT',
    path: '/Users/{id}',
    tag: 'Users',
    summary: '',
    auth: true,
    hasParams: true,
    ref: 'PUT /api/Users/{id}',
  },
  'weatherForecast.list': {
    method: 'GET',
    path: '/WeatherForecast',
    tag: 'WeatherForecast',
    summary: '',
    auth: true,
    hasParams: false,
    ref: 'GET /WeatherForecast',
  },
} as const satisfies Record<string, EndpointRecord>

export type ApiEndpointKey = keyof typeof API_ENDPOINTS
